Initial
k-dina/graduation_project pull request #19
Opened 2023-07-31 15:33 UTC by k-dina

2023-08-06 13:23 UTC, a-kosak-mbx requested changes

2023-08-06 13:23 UTC, a-kosak-mbx commented on processors/field_processor.py
> +def clamp(value, lower, upper) -> int:
Вообще можно использовать numpy clamp. Добавить numpy в список библиотек, а потом import numpy as np и np.clamp()

2023-08-06 13:23 UTC, a-kosak-mbx commented on processors/field_processor.py
> +        field = {key: value - 1 if value > 0 else value for (key, value) in field.items()}
Не будет работать. Ты ведь создаешь полностью новый словарь, а не обновляешь старый. И нигде новый не возвращаешь. Так что если хочешь, то можно очистить field, а потом вызвать на нем update. Но вообще в питоне принято возвращать значения.

2023-08-06 13:23 UTC, a-kosak-mbx commented on processors/field_processor.py
> +        field = {key: value - 1 if value > 0 else value for (key, value) in field.items()}
А вот это я вообще не очень-то понимаю.

2023-08-06 13:23 UTC, a-kosak-mbx commented on processors/harvesting_processor.py
> +def clamp(value, lower, upper) -> int:
Ну вот это уже точно лишнее. Если ты в каждом модуле используешь clamp, то лучше вынести этот метод в отдельный модуль, один раз его реализовать и дальше импортировать туда, где нужно использовать.

2023-08-06 13:23 UTC, a-kosak-mbx commented on processors/harvesting_processor.py
> +def floor(value):
Почему бы не заменить эту функцию на int() или math.trunc()?

2023-08-06 13:23 UTC, a-kosak-mbx commented on processors/harvesting_processor.py
> +def lerp(v1, v2, time):
numpy interp. Так вроде бы называется.

2023-08-06 13:23 UTC, a-kosak-mbx commented on processors/harvesting_processor.py
> +def vector_sum(first, second):
numpy.nparray.

2023-08-06 13:23 UTC, a-kosak-mbx commented on processors/harvesting_processor.py
> +        time += 0.2
Что за непонятная константа?

2023-08-06 13:23 UTC, a-kosak-mbx commented on processors/harvesting_processor.py
> +        print('get circle:', get_circle(result))
Принты убрать. Если хочешь что-то логировать, то используй библиотеку loguru и level debug.

2023-08-06 13:23 UTC, a-kosak-mbx commented on processors/harvesting_processor.py
> +    if distance <= 0:
Как дистанция может быть меньше 0?

2023-08-06 13:23 UTC, a-kosak-mbx commented on processors/harvesting_processor.py
> +    return np.random.choice(remaining_blobs, size=1, p=distribution.values())
А почему все эти функции вне класса процессора?

2023-08-06 13:23 UTC, a-kosak-mbx commented on processors/harvesting_processor.py
> +    return {arg: (arg['life'] + arg['vitality'] + arg['charisma']) / factor / len(args) for arg in args}
Почему бы не разделить один раз factor на len?

2023-08-06 13:23 UTC, a-kosak-mbx commented on processors/harvesting_processor.py
> +    distribution = success_prob(remaining_blobs)
Вот не понял, почему вычисляется именно так.

2023-08-06 13:23 UTC, a-kosak-mbx commented on processors/harvesting_processor.py
> +look_around.remove((0, 0))
В HarvestingProcessor в качестве константы.

2023-08-06 13:23 UTC, a-kosak-mbx commented on processors/health_speed_processor.py
> +    def process(self, blobs, other_blobs):
Не понимаю, что есть other_blobs?

2023-08-06 13:23 UTC, a-kosak-mbx commented on processors/health_speed_processor.py
> +                blobs.pop(int(blob['id']))
Зачем здесь int?

2023-08-06 13:23 UTC, a-kosak-mbx commented on processors/mating_processor.py
> +look_around.remove((0, 0))
Второй раз используется, нужно вынести в отдельный модуль и импортировать.

2023-08-06 13:23 UTC, a-kosak-mbx commented on processors/mating_processor.py
> +# from simulation import configuration, clamp
Ну так и импортировать.

2023-08-06 13:23 UTC, a-kosak-mbx commented on processors/mating_processor.py
> +def vector_sum(first, second):
numpy

2023-08-06 13:23 UTC, a-kosak-mbx commented on processors/mating_processor.py
> +    return 1 - distance - 0.2
Очень странная формула. distance может быть отрицательным. Непонятно, откуда вообще эти значения. Ну и нужно либо пояснить их, либо вынести в именованные константы (кроме 1).

2023-08-06 13:23 UTC, a-kosak-mbx commented on processors/mating_processor.py
> +        if location not in other_blobs:
Вот этот вот other пипец какое дурацкое название.

2023-08-06 13:23 UTC, a-kosak-mbx commented on processors/mating_processor.py
> +        for pair in pairs:
Разбей этот метод на несколько и именуй их так, чтобы было понятно, что вообще происходит. А то продираться через эти все blobs, blobs, blobs - это жесть.

2023-08-06 13:23 UTC, a-kosak-mbx commented on processors/mating_processor.py
> +    other_blob['freeze'] = 3
Почему эти методы вне класса MatingProcessor?

2023-08-06 13:23 UTC, a-kosak-mbx commented on simulation.py
>      return lower if value < lower else value if value < upper else upper
Опять clamp?

2023-08-06 13:23 UTC, a-kosak-mbx commented on simulation.py
> +mating_processor = MatingProcessor(configuration)
Это зачем? Выглядит довольно бессмысленным.

2023-08-07 16:59 UTC, k-dina commented on processors/harvesting_processor.py
> +    if distance <= 0:
если скорость больше расстояния

2023-08-07 16:59 UTC, k-dina commented on processors/harvesting_processor.py
> +    return np.random.choice(remaining_blobs, size=1, p=distribution.values())
а куда их?

2023-08-09 11:38 UTC, k-dina commented on processors/field_processor.py
> +def clamp(value, lower, upper) -> int:
потом проблемы с другими функциями из-за этого

2023-08-09 11:39 UTC, k-dina commented on processors/field_processor.py
> +        field = {key: value - 1 if value > 0 else value for (key, value) in field.items()}
там типа портилась еда. вынесла в отдельный метод

2023-08-09 11:41 UTC, k-dina commented on processors/harvesting_processor.py
> +    return {arg: (arg['life'] + arg['vitality'] + arg['charisma']) / factor / len(args) for arg in args}
уже сделала по-другому

2023-08-09 11:41 UTC, k-dina commented on processors/harvesting_processor.py
> +    distribution = success_prob(remaining_blobs)
потому что блобсы уходят. вероятность, что они останутся, равна вероятности их победы

2023-08-09 11:55 UTC, k-dina commented on processors/health_speed_processor.py
> +    def process(self, blobs, other_blobs):
переименовала. это слой поля с блобсами

2023-08-09 12:23 UTC, k-dina commented on processors/mating_processor.py
> +look_around.remove((0, 0))
с этим проблемки. разбираюсь

2023-08-12 08:43 UTC, a-kosak-mbx requested changes

2023-08-12 08:43 UTC, a-kosak-mbx commented on simulations/simulator/processors/harvesting_processor.py
> +        blobs[blob_id]['life'] = min(100, self.__life_increase)
Здесь точно не max нужен?

2023-08-12 08:43 UTC, a-kosak-mbx commented on simulations/simulator/configuration.py
> +def configure(parameters):
Здесь ожидается dict? Если ожидается dict, то лучше использовать что-то вроде
`configuration = copy(DEFAULT_CONFIGURATION)`
`configuration.update(parameters)`
`return configuration`

Или же, как вариант, если ты хочешь обновлять по полям
`configuration = copy(DEFAULT_CONFIGURATION)`
`configuration['field_fertility'] = parameters.get('field_fertility', configuration['field_fertility'])`
`...`
`return configuration`

2023-08-12 08:43 UTC, a-kosak-mbx commented on simulations/simulator/configuration.py
> +def get_initial_configuration():
Можно просто назвать DEFAULT_CONFIGURATION и убрать метод.

2023-08-12 08:43 UTC, a-kosak-mbx commented on simulations/simulator/mongo_db.py
> +    return collection.find_one({"step": step})
Лучше конфигурировать как-то так, то есть стандартно для джанго.
```
DATABASES = {
   'default' : {
      'ENGINE' : 'django_mongodb_engine',
      'NAME' : 'my_database'
   }
}
```

Дальше определяешь модель, так же, как и в джанго
```
class Post(models.Model):
    title = models.CharField()
    text = models.TextField()
    tags = ListField()
    comments = ListField()
```
и далее так же стандартно
```
post = Post.objects.create(
    title='Hello MongoDB!',
    text='Just wanted to drop a note from Django. Cya!',
    tags=['mongodb', 'django']
)

post.comments.extend(['Great post!', 'Please, do more of these!'])
post.save()
```

Посмотри вот тут https://django-mongodb-engine.readthedocs.io/en/latest/tutorial.html

2023-08-13 08:42 UTC, k-dina commented on simulations/simulator/processors/harvesting_processor.py
> +        blobs[blob_id]['life'] = min(100, self.__life_increase)
точно

2024-03-26 15:07 UTC, merged